# configuration for "master" branch
-
  branches:
    only:
      - master

  version: 1.0.{build}

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.cs'
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration:
    - Release

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore SS.Home.sln
    - gulp build

  build:
    project: SS.Home.sln       # path to Visual Studio solution or project
    publish_nuget: true

  artifacts:
    - path: '*.nupkg'

  deploy:
    - provider: NuGet
      server:                  # remove to push to NuGet.org
      api_key:
        secure: cKpWZvlfFA7EfagAXc/mZfTGHXxfoKNOYTQd6v4ImalbNV1mtNR55M2HMJJ4jCAo
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/

# configuration for "dev" branch
-
  branches:
    only:
      - dev

  version: 1.0.{build}-beta

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.cs'
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration:
    - Release

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore SS.Home.sln
    - gulp build

  build:
    project: SS.Home.sln       # path to Visual Studio solution or project
    publish_nuget: true

  artifacts:
    - path: '**/*.nupkg'

  deploy:
    - provider: NuGet
      server: https://www.myget.org/F/siteserver/api/v2/package                 # remove to push to NuGet.org
      api_key:
        secure: i9vISdFyCeWbRUQw+jhcF748i4oWdeatGBrx+dJ07SDTpt7Hsk9YCRp/ha3ZXfZF
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/

  notifications:
    - provider: Webhook
      url: http://api.siteserver.cn/v1.0/packages/SS.Home?isNightly=true
      headers:
        X-SiteServer-ApiKey:
          secure: BgJi7I52wZsaeoldjE1txzqjNWIqDwUUYzH5VFoVrZUW2NlSocZlSl1uXKE2PQut
      on_build_success: true